name: 'oci-token-exchange-action'
description: 'Exchange GitHub OIDC ID Token for OCI Session token for use in the GitHub Actions workflow job'
branding:
  color: red
  icon: cloud
inputs:
  ci_platform:
    description: 'CI platform (github, gitlab, or bitbucket)'
    required: false
    default: 'github'
  oidc_client_identifier:  
    description: 'OIDC Client Identifier'
    required: true
  domain_base_url:  
    description: 'Base URL of OCI Domain that provides the token exchange endpoint'
    required: true
  oci_tenancy:  
    description: 'OCI Tenancy'
    required: true
  oci_region:  
    description: 'OCI Region'
    required: true
  retry_count: 
    description: 'Number of times to retry the token exchange, default value of 0 means no retries'
    required: false
    default: '0'
runs:
  using: 'node20'
  main: 'dist/main.js'
