root: true
env:
  node: true
  es2021: true
  jest: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  sourceType: module

plugins:
  - '@typescript-eslint'
  - prettier

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

ignorePatterns:
  - dist/

rules:
  # Example rules, adjust as needed
  '@typescript-eslint/no-unused-vars': "warn"
  '@typescript-eslint/explicit-function-return-type': "off"
  'prettier/prettier': "off"
  'comma-dangle': [ "error", "never" ]
  # '@typescript-eslint/no-var-requires': "off"
