# Add this workflow to auto-update dist/ on releases
name: Build and Commit
on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. Checks out your repository code
    - uses: actions/checkout@v4
    
    # 2. Sets up Node.js environment
    - uses: actions/setup-node@v4
      with:
        node-version: '20'
    
    # 3. Installs dependencies (including @vercel/ncc for bundling)
    - run: npm ci
    
    # 4. Builds your action using ncc (creates dist/main.js and dist/cli.js)
    - run: npm run build
    
    # 5. Commits the built files back to the repository
    - name: Commit built files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add dist/                                    # Stage the built files
        git diff --staged --quiet || git commit -m "Build dist files"  # Only commit if changes exist
        git push                                         # Push back to main
